/**
 * Moduł sefirot-data.js
 * 
 * Zawiera dane o sefirach i ścieżkach Drzewa Życia.
 * Udostępnia funkcje inicjalizujące te struktury danych.
 */

// Eksportuj funkcje do innych modułów
export function initializeSefirot() {
  return {
    keter: {
      name: "Keter",
      hebrewName: "כתר",
      meaning: "Korona",
      aspect:
        "Najwyższa, pierwsza emanacja, reprezentująca czystą Boską wolę i potencjał",
      attributes: [
        "Jedność",
        "Transcendencja",
        "Niepoznawalność",
        "Nieskończoność",
      ],
      symbol: "Punkt, z którego wszystko się wyłania",
      consciousness: "Nadświadomość wykraczająca poza dualizm",
      column: "środkowa",
      level: "wyższy",
      color: "var(--keter-color)",
      position: { top: "5%", left: "50%" },
      epistemicQuestions: [
        "Co pozostałoby niezmienne w {zagadnieniu}, gdybyśmy zakwestionowali wszystkie jego pozornie fundamentalne założenia?",
        "Jakie transcendentne pytanie kryje się za wszystkimi pytaniami, które zadajemy o {zagadnieniu}?",
        "W jaki sposób pozornie przeciwstawne perspektywy na {zagadnienie} mogą być postrzegane jako różne aspekty tej samej, głębszej prawdy?",
        "Co by się stało, gdybyśmy przestali kategoryzować i dzielić {zagadnienie} na części, a spojrzeli na nie jako na niepodzielną całość?",
        "Jakie najgłębsze pragnienie lub cel leży u podstaw wszystkich działań i rozwoju związanego z {zagadnieniem}?",
      ],
      promptFormulas: [
        "Przekraczaj wszelkie dualistyczne kategorie i rozpoznaj pierwotną jedność leżącą u podstaw {zagadnienia}.",
        "Poszukaj tego, co pozostaje niezmienne w {zagadnieniu}, gdy wszystkie inne aspekty ulegają transformacji.",
        "Zidentyfikuj transcendentny cel stojący za pozorną różnorodnością elementów w {zagadnieniu}.",
      ],
    },
    chokmah: {
      name: "Chokmah",
      hebrewName: "חכמה",
      meaning: "Mądrość",
      aspect: "Pierwotna twórcza energia, pierwiastek męski",
      attributes: ["Inspiracja", "Intuicja", "Wgląd", "Spontaniczność"],
      symbol: "Nasienie zawierające potencjał wszystkich form",
      consciousness: "Błysk wglądu poprzedzający zrozumienie",
      column: "prawa",
      level: "wyższy",
      color: "var(--chokmah-color)",
      position: { top: "15%", left: "25%" },
      epistemicQuestions: [
        "Jakie radykalnie nowe perspektywy na {zagadnienie} mogłyby się pojawić, gdybyśmy całkowicie porzucili obecne ramy konceptualne?",
        "Co byś dostrzegł w {zagadnieniu}, gdybyś spojrzał na nie po raz pierwszy, bez żadnych uprzednich koncepcji czy oczekiwań?",
        "Jaki niekonwencjonalny wgląd w {zagadnienie} mógłby zrewolucjonizować całe pole?",
        "Jakie niezwykłe połączenia mogą istnieć między {zagadnieniem} a pozornie niezwiązanymi dziedzinami wiedzy?",
        "Gdybyś mógł całkowicie przekształcić sposób myślenia o {zagadnieniu}, jaką formę by przyjęło?",
      ],
      promptFormulas: [
        "Podejdź do {zagadnienia} z czystą intuicją, całkowicie zawieszając analityczne myślenie i istniejące kategorie.",
        "Wyobraź sobie najbardziej radykalną, transformującą ideę dotyczącą {zagadnienia}, jaka jeszcze nie została pomyślana.",
        "Pozwól, by z chaosu i nieporządku wyłoniły się nowe, generatywne wzorce dotyczące {zagadnienia}.",
      ],
    },
    binah: {
      name: "Binah",
      hebrewName: "בינה",
      meaning: "Zrozumienie",
      aspect: "Pierwiastek żeński, zdolność do analizy i strukturyzacji",
      attributes: ["Rozróżnianie", "Analiza", "Kontemplacja", "Forma"],
      symbol: "Łono, w którym rozwija się potencjał Chokmah",
      consciousness: "Refleksja, analiza, kategoryzacja",
      column: "lewa",
      level: "wyższy",
      color: "var(--binah-color)",
      position: { top: "15%", left: "75%" },
      epistemicQuestions: [
        "Jakie niewidoczne struktury i wzorce mogą organizować {zagadnienie}, które wymykają się powszechnej percepcji?",
        "W jaki sposób nasze obecne kategorie i ramy pojęciowe mogą ograniczać głębsze zrozumienie {zagadnienia}?",
        "Jakie nowe taksonomie lub systemy klasyfikacji mogłyby lepiej uchwycić naturę {zagadnienia}?",
        "Co ujawniłoby się, gdybyśmy zastosowali całkowicie odmienne metody analizy do {zagadnienia}?",
        "Jakie ukryte założenia kształtują sposób, w jaki obecnie strukturyzujemy i analizujemy {zagadnienie}?",
      ],
      promptFormulas: [
        "Zastosuj głęboką analizę strukturalną do {zagadnienia}, odkrywając ukryte wzorce i nieintuicyjne kategorie.",
        "Stwórz całkowicie nowy system konceptualny do mapowania i rozumienia {zagadnienia}.",
        "Odkryj granice i ograniczenia obecnych ram analitycznych stosowanych do {zagadnienia} i zaproponuj ich przekroczenie.",
      ],
    },
    chesed: {
      name: "Chesed",
      hebrewName: "חסד",
      meaning: "Miłosierdzie",
      aspect: "Bezwarunkowa miłość, łaska, ekspansja",
      attributes: ["Współczucie", "Hojność", "Inkluzywność"],
      symbol: "Otwarta dłoń dająca błogosławieństwo",
      consciousness: "Empatia, akceptacja, dobroć",
      column: "prawa",
      level: "środkowy",
      color: "var(--chesed-color)",
      position: { top: "30%", left: "25%" },
      epistemicQuestions: [
        "Jak mogłoby wyglądać {zagadnienie}, gdybyśmy zastosowali podejście radykalnej hojności i nieograniczonej otwartości?",
        "Jakie transformacyjne możliwości mogłyby się pojawić, gdybyśmy zawiesili wszelką krytykę i osąd wobec {zagadnienia}?",
        "W jaki sposób perspektywa bezwarunkowej akceptacji mogłaby zrewolucjonizować nasze podejście do {zagadnienia}?",
        "Co by się stało, gdybyśmy zastosowali zasadę obfitości zamiast zasady niedoboru do {zagadnienia}?",
        "Jak moglibyśmy poszerzyć granice {zagadnienia}, by objąć to, co obecnie wydaje się być poza jego zasięgiem?",
      ],
      promptFormulas: [
        "Rozpoznaj możliwości nieograniczonej ekspansji i wzrostu w {zagadnieniu}, przekraczając wszelkie postrzegane limity.",
        "Zastosuj perspektywę bezwarunkowej akceptacji, by odkryć ukryty potencjał w {zagadnieniu}.",
        "Wyobraź sobie świat, w którym zasoby związane z {zagadnieniem} są nieograniczone i powszechnie dostępne.",
      ],
    },
    gevurah: {
      name: "Gevurah",
      hebrewName: "גבורה",
      meaning: "Siła/Surowość",
      aspect: "Ograniczenie, osąd, dyscyplina",
      attributes: ["Sprawiedliwość", "Moc", "Oddzielenie"],
      symbol: "Zaciśnięta pięść, miecz",
      consciousness: "Krytyczna ocena, ustalanie granic",
      column: "lewa",
      level: "środkowy",
      color: "var(--gevurah-color)",
      position: { top: "30%", left: "75%" },
      epistemicQuestions: [
        "Jakie kluczowe rozróżnienia w {zagadnieniu} umykają naszej uwadze, które mogłyby przynieść przełom?",
        "Które elementy {zagadnienia} należałoby odrzucić lub przekształcić, by ujawnić jego prawdziwą istotę?",
        "Jakie rygorystyczne standardy lub kryteria mogłyby radykalnie podnieść jakość myślenia o {zagadnieniu}?",
        "W jaki sposób precyzyjne ustanowienie granic mogłoby paradoksalnie wyzwolić nowy potencjał w {zagadnieniu}?",
        "Co by się stało, gdybyśmy zastosowali bezlitosną, ale konstruktywną krytykę do każdego aspektu {zagadnienia}?",
      ],
      promptFormulas: [
        "Zastosuj rygorystyczną krytyczną analizę do {zagadnienia}, odrzucając wszystko, co nie wytrzymuje najsurowszej próby.",
        "Zidentyfikuj i zakwestionuj każde słabe ogniwo w łańcuchu rozumowania dotyczącego {zagadnienia}.",
        "Ustanów jasne, precyzyjne granice definiujące istotę {zagadnienia}, eliminując wszystko, co przypadkowe lub drugorzędne.",
      ],
    },
    tiferet: {
      name: "Tiferet",
      hebrewName: "תפארת",
      meaning: "Piękno",
      aspect: "Harmonijna integracja przeciwieństw, środkowa kolumna",
      attributes: ["Równowaga", "Prawda", "Współczucie", "Harmonia"],
      symbol: "Słońce, serce",
      consciousness: "Zintegrowana jaźń, całościowy wgląd",
      column: "środkowa",
      level: "środkowy",
      color: "var(--tiferet-color)",
      position: { top: "45%", left: "50%" },
      epistemicQuestions: [
        "W jaki sposób pozorne paradoksy i sprzeczności w {zagadnieniu} mogą wskazywać na głębszą, nierozpoznaną jeszcze harmonię?",
        "Jak mogłaby wyglądać wyższa synteza różnych, przeciwstawnych perspektyw na {zagadnienie}?",
        "Co stanowi prawdziwe 'serce' {zagadnienia} – centralny punkt, wokół którego wszystko inne się organizuje?",
        "Jakie nowe zrozumienie {zagadnienia} mogłoby pojawić się, gdybyśmy integrowali racjonalne i intuicyjne podejścia?",
        "W jaki sposób {zagadnienie} jawi się, gdy jest postrzegane jako dynamiczna całość, a nie zbiór oddzielnych części?",
      ],
      promptFormulas: [
        "Poszukaj wyższej syntezy, która integruje i transcenduje pozornie sprzeczne perspektywy na {zagadnienie}.",
        "Zidentyfikuj dynamiczną równowagę przeciwieństw, która leży u podstaw najgłębszej prawdy o {zagadnieniu}.",
        "Odkryj centralny punkt lub 'serce' {zagadnienia}, które łączy wszystkie jego aspekty w harmonijną całość.",
      ],
    },
    netzach: {
      name: "Netzach",
      hebrewName: "נצח",
      meaning: "Zwycięstwo",
      aspect: "Emocjonalna energia, trwałość",
      attributes: ["Pasja", "Pragnienie", "Witalność", "Entuzjazm"],
      symbol: "Ogień, kolor czerwony",
      consciousness: "Emocjonalna inteligencja, inspiracja",
      column: "prawa",
      level: "niższy",
      color: "var(--netzach-color)",
      position: { top: "60%", left: "25%" },
      epistemicQuestions: [
        "Jakie głębokie pragnienia i aspiracje kryją się za powszechnym zainteresowaniem {zagadnieniem}?",
        "W jaki sposób emocjonalny rezonans z {zagadnieniem} może prowadzić do wglądów niedostępnych przez czysto intelektualne podejście?",
        "Co sprawiłoby, że {zagadnienie} stałoby się źródłem nieustającej inspiracji i pasji?",
        "Jak {zagadnienie} mogłoby ewoluować, gdyby było napędzane przez autentyczne pragnienie, a nie tylko praktyczną konieczność?",
        "Jakie nieodkryte źródła emocjonalnej energii mogłyby zrewolucjonizować nasze podejście do {zagadnienia}?",
      ],
      promptFormulas: [
        "Odkryj głębokie, emocjonalne źródła energii, które mogą transformować i ożywiać {zagadnienie}.",
        "Zidentyfikuj fundamentalne pragnienia i aspiracje, które nadają {zagadnieniu} trwałe znaczenie i wartość.",
        "Zbadaj, jak autentyczna pasja może całkowicie przekształcić sposób, w jaki rozumiemy i angażujemy się w {zagadnienie}.",
      ],
    },
    hod: {
      name: "Hod",
      hebrewName: "הוד",
      meaning: "Chwała",
      aspect: "Intelektualna energia, forma",
      attributes: ["Komunikacja", "Analiza", "Porządek", "Struktura"],
      symbol: "Woda, kolor niebieski",
      consciousness: "Racjonalna inteligencja, konceptualizacja",
      column: "lewa",
      level: "niższy",
      color: "var(--hod-color)",
      position: { top: "60%", left: "75%" },
      epistemicQuestions: [
        "Jakie całkowicie nowe modele konceptualne mogłyby rewolucjonizować nasze rozumienie {zagadnienia}?",
        "W jaki sposób moglibyśmy radykalnie przekształcić język i terminologię używaną do opisu {zagadnienia}?",
        "Jakie alternatywne systemy logiczne mogłyby lepiej uchwycić złożoność {zagadnienia}?",
        "Co by się stało, gdybyśmy zakwestionowali i przeformułowali najbardziej podstawowe definicje w {zagadnieniu}?",
        "Jak moglibyśmy komunikować o {zagadnieniu} w sposób, który transformuje samo jego rozumienie?",
      ],
      promptFormulas: [
        "Stwórz całkowicie nowe ramy konceptualne i język do opisania {zagadnienia}, wykraczające poza konwencjonalne kategorie.",
        "Zastosuj niekonwencjonalne systemy logiczne i analityczne do odkrycia ukrytych wymiarów {zagadnienia}.",
        "Zakwestionuj i przeprojektuj fundamentalne definicje i modele teoretyczne dotyczące {zagadnienia}.",
      ],
    },
    yesod: {
      name: "Yesod",
      hebrewName: "יסוד",
      meaning: "Fundament",
      aspect: "Łącznik wszystkich wyższych energii",
      attributes: ["Integracja", "Podstawa", "Podświadomość"],
      symbol: "Księżyc, woda",
      consciousness: "Podświadomość, wyobraźnia, sny",
      column: "środkowa",
      level: "niższy",
      color: "var(--yesod-color)",
      position: { top: "75%", left: "50%" },
      epistemicQuestions: [
        "Jakie archetypy i symbole najgłębiej rezonują z istotą {zagadnienia} na poziomie zbiorowej nieświadomości?",
        "W jaki sposób nieświadome wzorce i założenia kształtują nasze rozumienie {zagadnienia}, pozostając niewidoczne?",
        "Jak mogłaby wyglądać mapa {zagadnienia} stworzona przez wyobraźnię zamiast analitycznego umysłu?",
        "Jakie sny, wizje lub intuicje mogłyby ujawnić ukryte wymiary {zagadnienia}?",
        "Co by się stało, gdybyśmy traktowali {zagadnienie} jako żywy symbol lub metaforę zamiast literalnego faktu?",
      ],
      promptFormulas: [
        "Eksploruj podświadome struktury i archetypy, które kształtują nasze fundamentalne rozumienie {zagadnienia}.",
        "Wykorzystaj aktywną wyobraźnię i symboliczną reprezentację, by odkryć ukryte wymiary {zagadnienia}.",
        "Traktuj {zagadnienie} jako żywy symbol lub metaforę, która objawia głębsze warstwy znaczenia.",
      ],
    },
    malkuth: {
      name: "Malkuth",
      hebrewName: "מלכות",
      meaning: "Królestwo",
      aspect: "Manifestacja materialna, świat fizyczny",
      attributes: ["Konkretyzacja", "Realizacja", "Obecność"],
      symbol: "Ziemia, wszystkie cztery żywioły",
      consciousness: "Świadomość cielesna, percepcja zmysłowa",
      column: "środkowa",
      level: "najniższy",
      color: "var(--malkuth-color)",
      position: { top: "90%", left: "50%" },
      epistemicQuestions: [
        "W jaki sposób {zagadnienie} manifestuje się w najbardziej konkretnych, namacalnych formach, które możemy bezpośrednio doświadczyć?",
        "Jak zmieniłoby się nasze rozumienie {zagadnienia}, gdybyśmy oparli je wyłącznie na bezpośrednim, zmysłowym doświadczeniu?",
        "Jakie materialne eksperymenty lub praktyczne działania mogłyby przynieść przełomowe odkrycia w {zagadnieniu}?",
        "W jaki sposób ciało i zmysłowe doświadczenie mogą stać się narzędziami badania {zagadnienia}?",
        "Jak abstrakcyjne aspekty {zagadnienia} mogą zostać przekształcone w konkretne, materialne manifestacje?",
      ],
      promptFormulas: [
        "Poszukaj konkretnych, namacalnych manifestacji {zagadnienia}, które można bezpośrednio doświadczyć zmysłami.",
        "Przekształć abstrakcyjne aspekty {zagadnienia} w materialne eksperymenty i praktyczne działania.",
        "Zakorzenij teoretyczne zrozumienie {zagadnienia} w bezpośrednim, cielesnym doświadczeniu i konkretnej rzeczywistości.",
      ],
    },
  };
}

export function initializePaths() {
    return {
      keter_chokmah: {
        start: "keter",
        end: "chokmah",
        letter: "א",
        letterName: "Alef",
        essence:
          "Przejście od nieskończonej potencjalności do pierwszej konkretyzacji",
        process: "Początkowa manifestacja Boskości w formie twórczej energii",
        transformation:
          "Od czystej jedności do pierwszych przebłysków dualności",
        challenge: "Zachowanie poczucia jedności przy pierwszym rozróżnieniu",
        element: "Powietrze",
        tarot: "Głupiec",
        epistemicQuestions: [
          "Jak utrzymać świadomość fundamentalnej jedności, jednocześnie badając różnorodne manifestacje {zagadnienia}?",
          "W jaki sposób czysta potencjalność może przekształcać się w konkretne, twórcze impulsy w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy postrzegali intuicyjne wglądy w {zagadnienie} jako bezpośrednie emanacje niepodzielnej całości?",
        ],
      },
      keter_binah: {
        start: "keter",
        end: "binah",
        letter: "ב",
        letterName: "Bet",
        essence: "Przejście od Boskiej woli do struktury i formy",
        process: "Krystalizacja abstrakcyjnego potencjału w konkretne wzorce",
        transformation: "Od czystej jedności do zrozumienia wielości",
        challenge: "Utrzymanie łączności z jednością podczas strukturyzacji",
        element: "Merkury",
        tarot: "Mag",
        epistemicQuestions: [
          "Jak pierwotna, niepodzielna całość może przejawiać się poprzez złożone struktury i systemy w {zagadnieniu}?",
          "W jaki sposób możemy zacząć kategoryzować i analizować {zagadnienie} bez utraty świadomości jego fundamentalnej niepodzielności?",
          "Co by się stało, gdybyśmy rozwijali strukturalne zrozumienie {zagadnienia}, jednocześnie pamiętając o jego transcendentnej naturze?",
        ],
      },
      keter_tiferet: {
        start: "keter",
        end: "tiferet",
        letter: "ג",
        letterName: "Gimel",
        essence: "Bezpośrednie połączenie Boskiej woli z harmonijnym centrum",
        process: "Ścieżka równowagi duchowej i bezpośredniego wglądu",
        transformation: "Doświadczenie Boskiej esencji w stanie równowagi",
        challenge: "Utrzymanie czystości kanału dla Boskiej energii",
        element: "Księżyc",
        tarot: "Arcykapłanka",
        epistemicQuestions: [
          "Jak możemy doświadczyć najwyższej jedności poprzez harmonijny środek w kontekście {zagadnienia}?",
          "W jaki sposób bezpośredni, intuicyjny wgląd w istotę {zagadnienia} może przekształcić nasze zrozumienie jego harmonijnej całości?",
          "Co by się stało, gdybyśmy poszukiwali zrównoważonego centrum {zagadnienia} jako ścieżki do jego transcendentnej natury?",
        ],
      },
      chokmah_binah: {
        start: "chokmah",
        end: "binah",
        letter: "ד",
        letterName: "Dalet",
        essence: "Integracja pierwiastka męskiego (Chokmah) z żeńskim (Binah)",
        process:
          "Twórcza energia znajdująca formę, nasienie zapładniające łono",
        transformation: "Synteza intuicji i analizy, wglądu i zrozumienia",
        challenge: "Harmonijne połączenie przeciwieństw bez dominacji",
        element: "Wenus",
        tarot: "Cesarzowa",
        epistemicQuestions: [
          "Jak możemy zintegrować błyskawiczne intuicyjne wglądy z rygorystyczną analizą strukturalną w podejściu do {zagadnienia}?",
          "W jaki sposób dynamiczna, twórcza energia może znaleźć swoją optymalną formę i strukturę w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy kultywowali płynną współpracę między spontaniczną kreatywnością a metodyczną analizą w badaniu {zagadnienia}?",
        ],
      },
      chokmah_tiferet: {
        start: "chokmah",
        end: "tiferet",
        letter: "ה",
        letterName: "He",
        essence: "Mądrość znajdująca wyraz poprzez harmonię i piękno",
        process: "Przepływ twórczej energii do zrównoważonego centrum",
        transformation: "Intuicyjne rozpoznanie harmonii i równowagi",
        challenge: "Zachowanie czystości wglądu w procesie integracji",
        element: "Baran",
        tarot: "Cesarz",
        epistemicQuestions: [
          "Jak pierwotne, twórcze impulsy mogą znaleźć harmonijny wyraz w zrównoważonym centrum {zagadnienia}?",
          "W jaki sposób błyskawiczny wgląd może prowadzić do głębokiej, zintegrowanej harmonii w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy pozwolili, aby intuicyjna mądrość spontanicznie układała się w harmonijne wzorce podczas badania {zagadnienia}?",
        ],
      },
      chokmah_chesed: {
        start: "chokmah",
        end: "chesed",
        letter: "ו",
        letterName: "Vav",
        essence: "Mądrość manifestująca się jako miłosierdzie i ekspansja",
        process: "Przepływ twórczej energii do sfery miłości i hojności",
        transformation: "Od czystego wglądu do współczującej perspektywy",
        challenge: "Mądre kierowanie energią ekspansji",
        element: "Byk",
        tarot: "Hierofant",
        epistemicQuestions: [
          "Jak możemy przekształcić błyskawiczne, intuicyjne wglądy w {zagadnienie} w pełne współczucia i hojności podejście?",
          "W jaki sposób twórcza energia może naturalnie prowadzić do ekspansji i wzrostu w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy połączyli niekonwencjonalne, intuicyjne idee z bezwarunkową akceptacją podczas eksploracji {zagadnienia}?",
        ],
      },
      binah_tiferet: {
        start: "binah",
        end: "tiferet",
        letter: "ז",
        letterName: "Zayin",
        essence: "Zrozumienie wyrażone poprzez harmonię i piękno",
        process: "Struktura znajdująca wyraz w zrównoważonej formie",
        transformation: "Od analitycznego pojmowania do zintegrowanego wglądu",
        challenge: "Przekroczenie ograniczeń struktur myślowych",
        element: "Bliźnięta",
        tarot: "Kochankowie",
        epistemicQuestions: [
          "W których momentach rozumienie analityczne {zagadnienia} musi ustąpić miejsca zintegrowanemu, intuicyjnemu wglądowi?",
          "Jak możemy przekształcić rygorystyczne struktury konceptualne w harmonijną, zrównoważoną całość w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali głębszej harmonii i piękna leżących u podstaw złożonych struktur {zagadnienia}?",
        ],
      },
      binah_gevurah: {
        start: "binah",
        end: "gevurah",
        letter: "ח",
        letterName: "Chet",
        essence: "Zrozumienie przejawiające się jako osąd i granice",
        process: "Wzmocnienie struktur poprzez dyscyplinę",
        transformation: "Rozpoznanie konieczności ograniczeń i form",
        challenge: "Uniknięcie nadmiernej surowości i sztywności",
        element: "Rak",
        tarot: "Rydwan",
        epistemicQuestions: [
          "Jak rygorystyczna analiza strukturalna może prowadzić do precyzyjnych, transformacyjnych rozróżnień w {zagadnieniu}?",
          "W jaki sposób ustanowienie jasnych granic i kryteriów może paradoksalnie wyzwolić głębsze zrozumienie {zagadnienia}?",
          "Co by się stało, gdybyśmy połączyli głęboką analizę strukturalną z surowym, bezkompromisowym osądem w badaniu {zagadnienia}?",
        ],
      },
      chesed_gevurah: {
        start: "chesed",
        end: "gevurah",
        letter: "ט",
        letterName: "Tet",
        essence: "Dynamiczna równowaga między miłosierdziem a surowością",
        process: "Wzajemne temperowanie ekspansji i ograniczenia",
        transformation:
          "Integracja przeciwstawnych sił dla etycznego działania",
        challenge: "Znalezienie złotego środka między nadmiarem i niedoborem",
        element: "Lew",
        tarot: "Siła",
        epistemicQuestions: [
          "Jak można zintegrować pozornie sprzeczne siły bezwarunkowej akceptacji i rygorystycznej oceny w podejściu do {zagadnienia}?",
          "W jaki sposób dynamiczne napięcie między ekspansją a ograniczeniem może stać się twórczą siłą w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali optymalnej, dynamicznej równowagi między hojnością a dyscypliną w badaniu {zagadnienia}?",
        ],
      },
      chesed_tiferet: {
        start: "chesed",
        end: "tiferet",
        letter: "י",
        letterName: "Yod",
        essence: "Miłosierdzie znajdując wyraz w harmonii",
        process: "Przepływ bezwarunkowej miłości do zrównoważonego centrum",
        transformation: "Od otwartości serca do zintegrowanej jaźni",
        challenge: "Zachowanie współczucia w równowadze z innymi jakościami",
        element: "Panna",
        tarot: "Pustelnik",
        epistemicQuestions: [
          "Jak bezwarunkowa akceptacja może prowadzić do głębszej, zrównoważonej harmonii w kontekście {zagadnienia}?",
          "W jaki sposób możemy zintegrować współczucie i otwartość z innymi perspektywami, tworząc pełniejsze zrozumienie {zagadnienia}?",
          "Co by się stało, gdybyśmy pozwolili, aby ekspansywna energia hojności znalazła swój zrównoważony wyraz w centrum {zagadnienia}?",
        ],
      },
      chesed_netzach: {
        start: "chesed",
        end: "netzach",
        letter: "כ",
        letterName: "Kaf",
        essence: "Miłosierdzie manifestujące się jako emocjonalna energia",
        process:
          "Ekspansywna energia miłości przekształcająca się w trwały entuzjazm",
        transformation: "Od bezwarunkowej akceptacji do inspiracji i pasji",
        challenge: "Zachowanie czystości uczuć i właściwe ich ukierunkowanie",
        element: "Jowisz",
        tarot: "Koło Fortuny",
        epistemicQuestions: [
          "Jak możemy przekształcić bezwarunkową akceptację w autentyczną pasję i inspirację w kontekście {zagadnienia}?",
          "W jaki sposób hojność i otwartość mogą stać się źródłem trwałej, emocjonalnej energii napędzającej {zagadnienie}?",
          "Co by się stało, gdybyśmy poszukiwali głębokich, emocjonalnych źródeł inspiracji, które rezonują z ekspansywną naturą {zagadnienia}?",
        ],
      },
      gevurah_tiferet: {
        start: "gevurah",
        end: "tiferet",
        letter: "ל",
        letterName: "Lamed",
        essence: "Surowy osąd zrównoważony przez harmonię",
        process: "Ograniczenie znajdące właściwe proporcje",
        transformation: "Od krytycznego rozróżnienia do wyważonej perspektywy",
        challenge: "Przekształcenie surowości w konstruktywną siłę",
        element: "Waga",
        tarot: "Sprawiedliwość",
        epistemicQuestions: [
          "Jak możemy przekształcić surowy osąd i krytyczne rozróżnienia w zrównoważoną, harmonijną perspektywę na {zagadnienie}?",
          "W jaki sposób rygorystyczne granice mogą paradoksalnie prowadzić do większej harmonii i piękna w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali idealnej proporcji między rygorystyczną dyscypliną a harmonijną integracją w badaniu {zagadnienia}?",
        ],
      },
      gevurah_hod: {
        start: "gevurah",
        end: "hod",
        letter: "מ",
        letterName: "Mem",
        essence: "Surowość wyrażona poprzez intelektualne struktury",
        process: "Osąd przekształcony w analityczną jasność",
        transformation: "Od krytycznego rozróżnienia do precyzyjnej myśli",
        challenge: "Uniknięcie nadmiernego intelektualizmu i krytycyzmu",
        element: "Woda",
        tarot: "Wisielec",
        epistemicQuestions: [
          "Jak możemy przekształcić surowy osąd w precyzyjną, intelektualną analizę, która transformuje nasze rozumienie {zagadnienia}?",
          "W jaki sposób rygorystyczne granice i kryteria mogą prowadzić do konceptualnej jasności i przejrzystości w kontekście {zagadnienia}?",
          "Co by się stało, gdybyśmy połączyli bezkompromisowy osąd z innowacyjnym myśleniem konceptualnym w badaniu {zagadnienia}?",
        ],
      },
      tiferet_netzach: {
        start: "tiferet",
        end: "netzach",
        letter: "נ",
        letterName: "Nun",
        essence: "Harmonia manifestująca się jako emocjonalne zwycięstwo",
        process: "Zrównoważona jaźń wyrażająca się poprzez entuzjazm i pasję",
        transformation: "Integracja emocji w harmonijną całość",
        challenge: "Zachowanie równowagi przy intensywnych emocjach",
        element: "Skorpion",
        tarot: "Śmierć",
        epistemicQuestions: [
          "Jak zrównoważona, harmonijna perspektywa może przekształcić się w autentyczną pasję i inspirację w kontekście {zagadnienia}?",
          "W jaki sposób centralne, integrujące zrozumienie może stać się źródłem emocjonalnej energii transformującej {zagadnienie}?",
          "Co by się stało, gdybyśmy poszukiwali emocjonalnych wyrazów głębokiej, zrównoważonej harmonii w badaniu {zagadnienia}?",
        ],
      },
      tiferet_yesod: {
        start: "tiferet",
        end: "yesod",
        letter: "ס",
        letterName: "Samech",
        essence: "Centralna harmonia łącząca się z fundamentem",
        process: "Przepływ zintegrowanej świadomości do podświadomości",
        transformation: "Harmonizacja świadomej jaźni z podświadomymi wzorcami",
        challenge: "Utrzymanie spójności podczas głębokiej transformacji",
        element: "Strzelec",
        tarot: "Umiarkowanie",
        epistemicQuestions: [
          "Jak zrównoważone, harmonijne zrozumienie może transformować głębokie, podświadome wzorce związane z {zagadnieniem}?",
          "W jaki sposób centralna, integrująca perspektywa może zakorzenić się w symbolicznej i wyobrażeniowej warstwie {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali połączenia między harmonijną świadomością a archetypowymi wymiarami {zagadnienia}?",
        ],
      },
      tiferet_hod: {
        start: "tiferet",
        end: "hod",
        letter: "ע",
        letterName: "Ayin",
        essence: "Harmonia wyrażona poprzez intelektualną jasność",
        process:
          "Zintegrowana świadomość przekładająca się na precyzyjne koncepcje",
        transformation: "Od harmonijnego centrum do jasnego wyrazu",
        challenge: "Zachowanie holistycznej perspektywy podczas analizy",
        element: "Koziorożec",
        tarot: "Diabeł",
        epistemicQuestions: [
          "Jak zrównoważone, harmonijne zrozumienie może znaleźć precyzyjny, intelektualny wyraz, który transformuje nasze myślenie o {zagadnieniu}?",
          "W jaki sposób centralna, integrująca perspektywa może być komunikowana poprzez innowacyjne koncepcje i modele {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali sposobów wyrażenia holistycznej harmonii poprzez analityczne struktury w badaniu {zagadnienia}?",
        ],
      },
      netzach_hod: {
        start: "netzach",
        end: "hod",
        letter: "פ",
        letterName: "Pe",
        essence: "Integracja emocji z intelektem",
        process: "Balansowanie pasji z racjonalnością",
        transformation: "Synteza uczucia i myśli, serca i umysłu",
        challenge:
          "Znalezienie dynamicznej równowagi między przeciwnymi energiami",
        element: "Mars",
        tarot: "Wieża",
        epistemicQuestions: [
          "Jak możemy zintegrować emocjonalną pasję z intelektualną precyzją, tworząc transformacyjne podejście do {zagadnienia}?",
          "W jaki sposób dynamiczne napięcie między emocjonalnym zaangażowaniem a analitycznym dystansem może prowadzić do przełomowych odkryć w {zagadnieniu}?",
          "Co by się stało, gdybyśmy poszukiwali twórczej syntezy serca i umysłu, uczucia i myśli w badaniu {zagadnienia}?",
        ],
      },
      netzach_yesod: {
        start: "netzach",
        end: "yesod",
        letter: "צ",
        letterName: "Tzaddi",
        essence: "Emocjonalna energia kanalizowana do fundamentu",
        process: "Przekształcanie uczuć w podświadome wzorce",
        transformation: "Integracja emocji z głębszymi poziomami psychiki",
        challenge: "Oczyszczenie emocjonalnych energii",
        element: "Wodnik",
        tarot: "Gwiazda",
        epistemicQuestions: [
          "Jak emocjonalna pasja i inspiracja mogą transformować głębokie, podświadome wzorce związane z {zagadnieniem}?",
          "W jaki sposób autentyczne pragnienia i aspiracje mogą kształtować symboliczną i wyobrażeniową warstwę {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali archetypowych obrazów i symboli, które rezonują z emocjonalną esencją {zagadnienia}?",
        ],
      },
      netzach_malkuth: {
        start: "netzach",
        end: "malkuth",
        letter: "ק",
        letterName: "Qof",
        essence:
          "Emocjonalne zwycięstwo manifestujące się w rzeczywistości fizycznej",
        process:
          "Bezpośrednie przełożenie energii pasji na działanie materialne",
        transformation: "Od uczucia do jego fizycznej ekspresji",
        challenge: "Zachowanie czystości intencji w materialnej manifestacji",
        element: "Ryby",
        tarot: "Księżyc",
        epistemicQuestions: [
          "Jak emocjonalną pasję i inspirację można przekształcić w konkretne, materialne manifestacje, które transformują rzeczywistość {zagadnienia}?",
          "W jaki sposób autentyczne pragnienia mogą znaleźć bezpośredni, fizyczny wyraz w praktycznych działaniach związanych z {zagadnieniem}?",
          "Co by się stało, gdybyśmy poszukiwali namacalnych, materialnych form dla emocjonalnej esencji {zagadnienia}?",
        ],
      },
      hod_yesod: {
        start: "hod",
        end: "yesod",
        letter: "ר",
        letterName: "Resh",
        essence: "Intelektualna jasność wpływająca na fundament",
        process: "Myśli kształtujące podświadome wzorce",
        transformation: "Integracja racjonalnego myślenia z podświadomością",
        challenge: "Przełożenie jasności konceptualnej na głębszy poziom",
        element: "Słońce",
        tarot: "Słońce",
        epistemicQuestions: [
          "Jak precyzyjne, intelektualne koncepcje mogą transformować głębokie, podświadome wzorce związane z {zagadnieniem}?",
          "W jaki sposób innowacyjne modele konceptualne mogą wpływać na symboliczną i wyobrażeniową warstwę {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali sposobów przełożenia jasnych idei na głębokie, archetypowe wymiary {zagadnienia}?",
        ],
      },
      hod_malkuth: {
        start: "hod",
        end: "malkuth",
        letter: "ש",
        letterName: "Shin",
        essence:
          "Intelektualna chwała manifestująca się w fizycznej rzeczywistości",
        process: "Przełożenie idei na konkretne formy",
        transformation: "Od abstrakcyjnej myśli do materialnego wyrazu",
        challenge: "Zachowanie integralności idei w procesie materializacji",
        element: "Ogień",
        tarot: "Sąd Ostateczny",
        epistemicQuestions: [
          "Jak precyzyjne, intelektualne koncepcje mogą być przekształcone w konkretne, materialne manifestacje, które transformują rzeczywistość {zagadnienia}?",
          "W jaki sposób innowacyjne modele teoretyczne mogą znaleźć bezpośredni, fizyczny wyraz w praktycznych aplikacjach {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali materialnych form dla najbardziej abstrakcyjnych aspektów {zagadnienia}?",
        ],
      },
      yesod_malkuth: {
        start: "yesod",
        end: "malkuth",
        letter: "ת",
        letterName: "Tav",
        essence: "Fundament bezpośrednio łączący się z fizyczną manifestacją",
        process: "Ostateczna materializacja wszystkich wyższych energii",
        transformation: "Od wyobrażenia do realizacji",
        challenge: "Czyste przełożenie wizji na rzeczywistość",
        element: "Saturn",
        tarot: "Świat",
        epistemicQuestions: [
          "Jak podświadome wzorce, symbole i archetypy mogą znaleźć konkretne, materialne wyrazy, które transformują rzeczywistość {zagadnienia}?",
          "W jaki sposób wyobrażeniowe, symboliczne wymiary mogą być przełożone na praktyczne działania i namacalne manifestacje {zagadnienia}?",
          "Co by się stało, gdybyśmy poszukiwali pełnej materializacji głębokich, archetypowych wymiarów {zagadnienia}?",
        ],
      },
    }
  }
